<a href="https://colab.research.google.com/github/kng14/Data-Analysis-from-codecamp/blob/main/data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import pandas as pd

In [11]:
falsy_values = (0, False, None, '', [], {})

In [12]:
any(falsy_values)


False

In [13]:
np.nan

nan

In [14]:
3 + np.nan

nan

In [15]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [16]:
a.sum()

nan

In [17]:
a.mean()

nan

In [18]:
3 + None

TypeError: ignored

In [19]:
a = np.array([1, 2, 3, np.nan, None, 4], dtype='float')

In [20]:
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [21]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [22]:
a.mean()

nan

In [23]:
a.sum()

nan

In [24]:
np.inf

inf

In [25]:
3 + np.inf

inf

In [26]:
np.inf / 3

inf

In [27]:
np.inf / np.inf

nan

In [28]:
b = np.array([1, 2, 3, np.inf, np.nan, 4], dtype=np.float)

In [29]:
b.sum()

nan

In [30]:
np.isnan(np.nan)

True

In [31]:
np.isinf(np.inf)

True

In [32]:
np.isfinite(np.nan), np.isfinite(np.inf)

(False, False)

In [33]:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False,  True, False, False])

In [34]:
np.isinf(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False, False,  True, False])

In [35]:
np.isfinite(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([ True,  True,  True, False, False,  True])

In [36]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [37]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

In [38]:
a[np.isfinite(a)]

array([1., 2., 3., 4.])

In [39]:
a[np.isfinite(a)].sum()

10.0

In [40]:
a[np.isfinite(a)].mean()

2.5